export const reservationErrorCodes = {
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_DB_ERROR: 'RESERVATION_DB_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SEAT_HOLD_EXPIRED: 'SEAT_HOLD_EXPIRED',
  SEAT_NOT_HELD: 'SEAT_NOT_HELD',
  DB_TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
  INVALID_CONCERT: 'INVALID_CONCERT',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',
  CANCELLATION_FAILED: 'CANCELLATION_FAILED',
} as const;

type ReservationErrorValue =
  (typeof reservationErrorCodes)[keyof typeof reservationErrorCodes];

export type ReservationServiceError = ReservationErrorValue;
